phase: train
model_save_name: ./saved/weights/sk_wgan
val_save_name: ./saved/skeleton


train_feeder_args:
  data_path: ./ntu120/xset/train_data_joint.npy
  label_path: ./ntu120/xset/train_label.pkl

gen_model_args:
  in_channels: 3
  joint_num: 25

dis_model_args:
  in_channels: 3
  joint_num: 25

base_lr: 0.1
weight_decay: 0.0005
epoch: 1000
step: [500, 800]
device: [0,1,2,3]
batch_size: 1024
